=== Nirmisha-Bollampalli/USC_Projects/DatabaseSystems/XQuery/SourceCode/Product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ProductInformation">
		<xs:annotation>
			<xs:documentation>Product Schema Definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Product" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ID" type="xs:integer" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Condition" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Price" type="xs:float" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Production_Date"  minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Month" type="xs:integer" minOccurs="1" maxOccurs="1"/>
										<xs:element name="Day" type="xs:integer" minOccurs="1" maxOccurs="1"/>
										<xs:element name="Year" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Nirmisha-Bollampalli/USC_Projects/DatabaseSystems/XQuery/SourceCode/Product.xml
<?xml version="1.0" encoding="UTF-8"?>
  <ProductInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Product.xsd">
  <Product>

  <ID>1 </ID>
  <Title>P1</Title>
  <Condition>New</Condition>
  <Price>120</Price>
  
  <Production_Date> 
	  <Month>10</Month>
	  <Day>-2</Day>
	  <Year>-2011</Year>  
	   </Production_Date>
  
  </Product> 
  <Product>

  <ID>2</ID>
  <Title>P2</Title>
  <Condition>New</Condition>
  <Price>300</Price>
  
  <Production_Date> 
	  <Month>8</Month>
	  <Day>-5</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>3 </ID>
  <Title>P3</Title>
  <Condition>New</Condition>
  <Price>60 </Price>
  
  <Production_Date> 
	  <Month>2</Month>
	  <Day>-5</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID> 4</ID>
  <Title>P4</Title>
  <Condition>old</Condition>
  <Price>40</Price>
  
  <Production_Date> 
	  <Month>5</Month>
	  <Day>-27</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>5</ID>
  <Title>P5</Title>
  <Condition>old</Condition>
  <Price>50</Price>
  
  <Production_Date> 
	  <Month>9</Month>
	  <Day>-16</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>6</ID>
  <Title>P6</Title>
  <Condition>old</Condition>
  <Price>20</Price>
  
  <Production_Date> 
	  <Month>1</Month>
	  <Day>-6</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>7</ID>
  <Title>P7</Title>
  <Condition>New</Condition>
  <Price> 40</Price>
  
  <Production_Date> 
	  <Month>4</Month>
	  <Day>-28</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>8</ID>
  <Title>P8</Title>
  <Condition>New</Condition>
  <Price>20</Price>
  
  <Production_Date> 
	  <Month>8</Month>
	  <Day>-18</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>9</ID>
  <Title>P9 </Title>
  <Condition>New</Condition>
  <Price>10</Price>
  
  <Production_Date> 
	  <Month>8</Month>
	  <Day>-12</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>10</ID>
  <Title>P10</Title>
  <Condition>New</Condition>
  <Price>25</Price>
  
  <Production_Date> 
	  <Month>3</Month>
	  <Day>-30</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>11</ID>
  <Title>P11</Title>
  <Condition>New</Condition>
  <Price>58</Price>
  
  <Production_Date> 
	  <Month>7</Month>
	  <Day>-20</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>12</ID>
  <Title>P12</Title>
  <Condition>New</Condition>
  <Price>89</Price>
  
  <Production_Date> 
	  <Month>11</Month>
	  <Day>-9</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>13</ID>
  <Title>P13</Title>
  <Condition>Old</Condition>
  <Price>10</Price>
  
  <Production_Date> 
	  <Month>3</Month>
	  <Day>-1</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>14</ID>
  <Title>P14</Title>
  <Condition>Old</Condition>
  <Price>10</Price>
  
  <Production_Date> 
	  <Month>6</Month>
	  <Day>-21</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>15</ID>
  <Title>P15</Title>
  <Condition>New</Condition>
  <Price>35</Price>
  
  <Production_Date> 
	  <Month>10 </Month>
	  <Day>-11</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>16</ID>
  <Title>P16 </Title>
  <Condition>Old</Condition>
  <Price>65</Price>
  
  <Production_Date> 
	  <Month>1</Month>
	  <Day>-31</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
 
  <Product>

  <ID>17</ID>
  <Title>P17</Title>
  <Condition>Old</Condition>
  <Price>75</Price>
  
  <Production_Date> 
	  <Month>5</Month>
	  <Day>-22</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>18</ID>
  <Title>P18</Title>
  <Condition>New</Condition>
  <Price>40</Price>
  
  <Production_Date> 
	  <Month>9</Month>
	  <Day>-11</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>19</ID>
  <Title>P19</Title>
  <Condition>New</Condition>
  <Price>40</Price>
  
  <Production_Date> 
	  <Month>1</Month>
	  <Day>-1</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>20</ID>
  <Title>P20</Title>
  <Condition>New</Condition>
  <Price>50</Price>
  
  <Production_Date> 
	  <Month>4</Month>
	  <Day>-23</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>21</ID>
  <Title>P21</Title>
  <Condition>Old</Condition>
  <Price> 80</Price>
  
  <Production_Date> 
	  <Month>8</Month>
	  <Day>-13</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>22</ID>
  <Title>P22</Title>
  <Condition>Old</Condition>
  <Price>80</Price>
  
  <Production_Date> 
	  <Month>12</Month>
	  <Day>-3</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>23</ID>
  <Title>P23</Title>
  <Condition>Old</Condition>
  <Price>90</Price>
  
  <Production_Date> 
	  <Month>3</Month>
	  <Day>-25</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  <Product>

  <ID>24</ID>
  <Title>P24</Title>
  <Condition>Old</Condition>
  <Price>100</Price>
  
  <Production_Date> 
	  <Month>7</Month>
	  <Day>-15</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  
  <Product>

  <ID>25</ID>
  <Title>P25</Title>
  <Condition>New</Condition>
  <Price>150</Price>
  
  <Production_Date> 
	  <Month>11</Month>
	  <Day>-4</Day>
	  <Year>-2011</Year>  
  </Production_Date>
  
  </Product> 
  
  
  </ProductInformation>
