=== Nirmisha-Bollampalli/USC_Projects/DatabaseSystems/XQuery/SourceCode/Review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (http://www.altova.com) by Nirmisha Bollampalli (USC) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ReviewInformation">
		<xs:annotation>
			<xs:documentation>Review Schema Definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Review" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ReviewNumber" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="ProductTitle" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Rating" >
											   <xs:simpleType>
												  <xs:restriction base="xs:integer">
												  <xs:minInclusive value="1"/>
												  <xs:maxInclusive value="5"/>
												  </xs:restriction>
											  </xs:simpleType>		
							</xs:element>						  							
							<xs:element name="Reviewer" type="xs:integer" minOccurs="1" maxOccurs="1"/>
							<xs:element name="ReviewDate" minOccurs="1" maxOccurs="1">
							      <xs:complexType>
									<xs:sequence>
										<xs:element name="Month" type="xs:integer" minOccurs="1" maxOccurs="1"/>
										<xs:element name="Day" type="xs:integer" minOccurs="1" maxOccurs="1"/>
										<xs:element name="Year" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="ReviewDescription"  type="xs:string" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Nirmisha-Bollampalli/USC_Projects/DatabaseSystems/XQuery/SourceCode/Review.xml
<?xml version="1.0" encoding="UTF-8"?>
  <ReviewInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Review.xsd">
  <Review>

  <ReviewNumber>R1</ReviewNumber>
  <ProductTitle>P1</ProductTitle>
  <Rating>3</Rating>
  <Reviewer>1</Reviewer>
  <ReviewDate>
		  <Month>11</Month>
		  <Day>-7</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Average</ReviewDescription>
  
  </Review> 
  
  <Review>

  <ReviewNumber>R2</ReviewNumber>
  <ProductTitle>P1</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>12</Month>
		  <Day>-6</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>  </ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R3</ReviewNumber>
  <ProductTitle>P1</ProductTitle>
  <Rating>1</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>2</Month>
		  <Day>-10</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R4</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>5</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>4</Month>
		  <Day>-21</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Excellent</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R5</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>3</Reviewer>
  <ReviewDate>
		  <Month>3</Month>
		  <Day>-17</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R6</ReviewNumber>
  <ProductTitle>P1</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>1</Reviewer>
  <ReviewDate>
		  <Month>7</Month>
		  <Day>-24</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R7</ReviewNumber>
  <ProductTitle>P3</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>1</Reviewer>
  <ReviewDate>
		  <Month>10</Month>
		  <Day>-31</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription> </ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R8</ReviewNumber>
  <ProductTitle>P4</ProductTitle>
  <Rating>3</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>8</Month>
		  <Day>-9</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R9</ReviewNumber>
  <ProductTitle>P4</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>4</Reviewer>
  <ReviewDate>
		  <Month>1</Month>
		  <Day>-12</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Below Average</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R10</ReviewNumber>
  <ProductTitle>P1</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>4</Reviewer>
  <ReviewDate>
		  <Month>10</Month>
		  <Day>-11</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R11</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>5</Reviewer>
  <ReviewDate>
		  <Month>12</Month>
		  <Day>-27</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R12</ReviewNumber>
  <ProductTitle>P5</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>5</Reviewer>
  <ReviewDate>
		  <Month>6</Month>
		  <Day>-25</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R13</ReviewNumber>
  <ProductTitle>P6</ProductTitle>
  <Rating>5</Rating>
  <Reviewer>1</Reviewer>
  <ReviewDate>
		  <Month>4</Month>
		  <Day>-25</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Below Average</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R14</ReviewNumber>
  <ProductTitle>P6</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-12</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R15</ReviewNumber>
  <ProductTitle>P7</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-26</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription> </ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R16</ReviewNumber>
  <ProductTitle>P12</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>6</Reviewer>
  <ReviewDate>
		  <Month>7</Month>
		  <Day>-2</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Below Average</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R17</ReviewNumber>
  <ProductTitle>P13</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>6</Reviewer>
  <ReviewDate>
		  <Month>7</Month>
		  <Day>-12</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R18</ReviewNumber>
  <ProductTitle>P9</ProductTitle>
  <Rating>1</Rating>
  <Reviewer>3</Reviewer>
  <ReviewDate>
		  <Month>7</Month>
		  <Day>-7</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R19</ReviewNumber>
  <ProductTitle>P10</ProductTitle>
  <Rating>5</Rating>
  <Reviewer>7</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-1</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Good</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R20</ReviewNumber>
  <ProductTitle>P10</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>7</Reviewer>
  <ReviewDate>
		  <Month>12</Month>
		  <Day>-26</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription> </ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R21</ReviewNumber>
  <ProductTitle>P1</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>7</Reviewer>
  <ReviewDate>
		  <Month>5</Month>
		  <Day>-1</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R22</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>3</Rating>
  <Reviewer>8</Reviewer>
  <ReviewDate>
		  <Month>12</Month>
		  <Day>-28</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R23</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>8</Reviewer>
  <ReviewDate>
		  <Month>3</Month>
		  <Day>-17</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R24</ReviewNumber>
  <ProductTitle>P10</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>3</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-11</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Poor</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R25</ReviewNumber>
  <ProductTitle>P10</ProductTitle>
  <Rating>1</Rating>
  <Reviewer>4</Reviewer>
  <ReviewDate>
		  <Month>12</Month>
		  <Day>-28</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R26</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>2</Reviewer>
  <ReviewDate>
		  <Month>10</Month>
		  <Day>-30</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R27</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>1</Reviewer>
  <ReviewDate>
		  <Month>5</Month>
		  <Day>-5</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R28</ReviewNumber>
  <ProductTitle>P2</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>1</Reviewer>
  <ReviewDate>
		  <Month>7</Month>
		  <Day>-30</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R29</ReviewNumber>
  <ProductTitle>P3</ProductTitle>
  <Rating>3</Rating>
  <Reviewer>8</Reviewer>
  <ReviewDate>
		  <Month>11</Month>
		  <Day>-1</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R30</ReviewNumber>
  <ProductTitle>P4</ProductTitle>
  <Rating>5</Rating>
  <Reviewer>9</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-5</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription> </ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R31</ReviewNumber>
  <ProductTitle>P4</ProductTitle>
  <Rating>5</Rating>
  <Reviewer>10</Reviewer>
  <ReviewDate>
		  <Month>7</Month>
		  <Day>-21</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Excellent</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R32</ReviewNumber>
  <ProductTitle>P20</ProductTitle>
  <Rating>3</Rating>
  <Reviewer>10</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-27</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R33</ReviewNumber>
  <ProductTitle>P5</ProductTitle>
  <Rating>2</Rating>
  <Reviewer>10</Reviewer>
  <ReviewDate>
		  <Month>11</Month>
		  <Day>-2</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription>Average</ReviewDescription>
  
  </Review> 
  <Review>

  <ReviewNumber>R34</ReviewNumber>
  <ProductTitle>P6</ProductTitle>
  <Rating>4</Rating>
  <Reviewer>10</Reviewer>
  <ReviewDate>
		  <Month>9</Month>
		  <Day>-20</Day>
		  <Year>-2012</Year>  
    </ReviewDate>		  
  <ReviewDescription></ReviewDescription>
